services:
  wish-template:
    build: 
      context: .
      args:
        - GIT_TAG=${GIT_TAG:-dev}
    image: ascii-arcade/wish-template:${GIT_TAG:-dev}
    ports:
      - "23234:23234"
    restart: always
    environment:
      - ASCII_ARCADE_SSH_PORT=23234
      - ASCII_ARCADE_HOST=0.0.0.0
    volumes:
      - wish-template_ssh:/app/.ssh
volumes:
  wish-template_ssh:
